### ISSUE TITLE
can this be extended to image to video?

### ISSUE THREAD

**Issue by SkylerZheng** [jianzongwu/MotionBooth#4]
wondering if this can be extended to image to video generation with image condition, and controllable camera motion?

**Comment by jianzongwu** [comment]
Our camera motion module is highly scalable. For vanilla text-to-video generation, you can directly use it and control the camera motion.

Since Stable Diffusion Pipeline does not provide image-to-video itself, you may need to find some image-to-video methods, like Stable Video Diffusion, and apply our camera motion method.

Please let me know if you success!
